all:
	g++ -O3 -Wall -DIMPL1 impl.cpp -o busca-local-1
	g++ -O3 -Wall -DIMPL1 impl.cpp -fopenmp -o busca-local-1-par

	g++ -O3 -Wall -DIMPL2 impl.cpp -o busca-local-2
	g++ -O3 -Wall -DIMPL2 impl.cpp -fopenmp -o busca-local-2-par


